//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.TechChallenge.Foundation.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiap.TechChallenge.Foundation.Core.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro não esperado..
        /// </summary>
        public static string API_001 {
            get {
                return ResourceManager.GetString("API_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação expirada..
        /// </summary>
        public static string API_002 {
            get {
                return ResourceManager.GetString("API_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não permitido..
        /// </summary>
        public static string API_003 {
            get {
                return ResourceManager.GetString("API_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;{0}&apos; deve ser do tipo &apos;{1}&apos;..
        /// </summary>
        public static string ArgumentMustBeType {
            get {
                return ResourceManager.GetString("ArgumentMustBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade {0} é obrigatória.
        /// </summary>
        public static string COR_001 {
            get {
                return ResourceManager.GetString("COR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validações.
        /// </summary>
        public static string COR_002 {
            get {
                return ResourceManager.GetString("COR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho máximo excedido - {0}..
        /// </summary>
        public static string COR_003 {
            get {
                return ResourceManager.GetString("COR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser maior do que - {0}..
        /// </summary>
        public static string COR_004 {
            get {
                return ResourceManager.GetString("COR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento {0} não informado..
        /// </summary>
        public static string COR_005 {
            get {
                return ResourceManager.GetString("COR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumento {0} deve iniciar com {1}..
        /// </summary>
        public static string COR_006 {
            get {
                return ResourceManager.GetString("COR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser igual a {0}..
        /// </summary>
        public static string COR_007 {
            get {
                return ResourceManager.GetString("COR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser diferente de {0}..
        /// </summary>
        public static string COR_008 {
            get {
                return ResourceManager.GetString("COR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve estar entre os valores {0} e {1}..
        /// </summary>
        public static string COR_009 {
            get {
                return ResourceManager.GetString("COR_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Email inválido..
        /// </summary>
        public static string COR_010 {
            get {
                return ResourceManager.GetString("COR_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Url inválido..
        /// </summary>
        public static string COR_011 {
            get {
                return ResourceManager.GetString("COR_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf {0} está inválido..
        /// </summary>
        public static string COR_012 {
            get {
                return ResourceManager.GetString("COR_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj {0} está inválido..
        /// </summary>
        public static string COR_013 {
            get {
                return ResourceManager.GetString("COR_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando {0} sem configuração de rota definida - EndpointConfiguration.Route..
        /// </summary>
        public static string COR_014 {
            get {
                return ResourceManager.GetString("COR_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRO.
        /// </summary>
        public static string COR_015 {
            get {
                return ResourceManager.GetString("COR_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponibilidade temporária, tente novamente!.
        /// </summary>
        public static string InfrastructureExceptionRetryMessage {
            get {
                return ResourceManager.GetString("InfrastructureExceptionRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar o reprocessamento do lote..
        /// </summary>
        public static string MessagingRequeueFail {
            get {
                return ResourceManager.GetString("MessagingRequeueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Email inválido..
        /// </summary>
        public static string ValidationEmailProperty {
            get {
                return ResourceManager.GetString("ValidationEmailProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser menor que {1}.
        /// </summary>
        public static string ValidationMaxLengthProperty {
            get {
                return ResourceManager.GetString("ValidationMaxLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser maior que {1}.
        /// </summary>
        public static string ValidationMinLengthProperty {
            get {
                return ResourceManager.GetString("ValidationMinLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade {0} deve estar entre os valores {1} e {2}..
        /// </summary>
        public static string ValidationRangeProperty {
            get {
                return ResourceManager.GetString("ValidationRangeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade {0} é obrigatória..
        /// </summary>
        public static string ValidationRequiredProperty {
            get {
                return ResourceManager.GetString("ValidationRequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade {0} excedeu o tamanho máximo {1}..
        /// </summary>
        public static string ValidationStringLengthProperty {
            get {
                return ResourceManager.GetString("ValidationStringLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Url inválido..
        /// </summary>
        public static string ValidationUrlProperty {
            get {
                return ResourceManager.GetString("ValidationUrlProperty", resourceCulture);
            }
        }
    }
}
