# .github/workflows/dotnet-ci.yml
name: .NET 8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies for solution
      run: dotnet restore fiap-postech-net-tech-challenge-01/src/Fiap.TechChallenge.sln

    - name: Build entire solution
      run: dotnet build Fiap.TechChallenge.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test fiap-postech-net-tech-challenge-01/src/Fiap.TechChallenge.sln --configuration Release --no-build --verbosity normal

    - name: Publish API project
      run: dotnet publish fiap-postech-net-tech-challenge-01/src/Fiap.TechChallenge.Api --configuration Release --output ./artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: api-artifacts
        path: ./artifacts
